import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

/**
 * AI feature type — extensible for future AI capabilities
 */
export enum AIFeatureType {
  BRIEFING_GENERATION = 'briefing_generation',
  MISSION_SUMMARY = 'mission_summary',
}

/**
 * AI Usage Tracking Entity
 *
 * Tracks AI generation usage per organization per day for rate limiting
 * and usage analytics. Each row represents one calendar day's usage
 * for a specific organization and AI feature.
 *
 * Rate limits:
 * - Briefing generation: 50/org/day (configurable via AI_BRIEFING_MAX_DAILY_PER_ORG)
 *
 * Token tracking:
 * - promptTokens: tokens sent to the model
 * - completionTokens: tokens generated by the model
 * - totalTokens: sum of both
 */
@Entity('ai_usage_tracking')
@Index(['organizationId', 'featureType', 'usageDate'], { unique: true })
@Index(['organizationId', 'usageDate'])
export class AIUsageTracking {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  /** Organization (tenant) this usage belongs to */
  @Column()
  organizationId!: string;

  /** Which AI feature was used */
  @Column({ type: 'enum', enum: AIFeatureType, default: AIFeatureType.BRIEFING_GENERATION })
  featureType!: AIFeatureType;

  /** Calendar date of usage (YYYY-MM-DD) for daily aggregation */
  @Column({ type: 'date' })
  usageDate!: string;

  /** Number of AI generation requests made today */
  @Column({ type: 'int', default: 0 })
  requestCount!: number;

  /** Total prompt tokens consumed today */
  @Column({ type: 'int', default: 0 })
  promptTokens!: number;

  /** Total completion tokens generated today */
  @Column({ type: 'int', default: 0 })
  completionTokens!: number;

  /** Total tokens (prompt + completion) consumed today */
  @Column({ type: 'int', default: 0 })
  totalTokens!: number;

  /** Last model used for requests this day */
  @Column({ type: 'varchar', length: 100, nullable: true })
  lastModelUsed?: string;

  /** ID of the last user who triggered a generation */
  @Column({ type: 'varchar', nullable: true })
  lastRequestByUserId?: string;

  @CreateDateColumn()
  createdAt!: Date;

  @UpdateDateColumn()
  updatedAt!: Date;
}
