import {
  DEFAULT_FLAG_SEVERITY,
  FlagSeverity,
  FlagStatus,
  MemberFlagType,
} from '@sc-fleet-manager/shared-types';
import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

import { TenantEntity } from './base/TenantEntity';

/**
 * MemberAuditEvent
 *
 * Persisted behavioral flag raised when a member performs a notable action
 * (leave org, get moderated, join watchlisted org, etc.).
 *
 * Scoped per organization — the same user can have different flags
 * in different orgs.
 *
 * Wave 2.1 — Membership Audit & Intel
 */
@Entity('member_audit_events')
@Index(['organizationId', 'userId'])
@Index(['organizationId', 'status'])
@Index(['organizationId', 'flagType'])
@Index(['organizationId', 'severity'])
@Index(['organizationId', 'createdAt'])
@Index(['userId', 'flagType'])
@Index(['status'])
export class MemberAuditEvent extends TenantEntity {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  /**
   * The user this flag is about.
   * References User.id but no FK — user may be deleted (GDPR).
   */
  @Index()
  @Column({ type: 'varchar' })
  userId!: string;

  /**
   * Type of behavioral event that triggered this flag.
   */
  @Column({
    type: 'varchar',
    length: 40,
  })
  flagType!: MemberFlagType;

  /**
   * Severity level.
   */
  @Column({
    type: 'varchar',
    length: 10,
  })
  severity!: FlagSeverity;

  /**
   * Resolution status.
   */
  @Column({
    type: 'varchar',
    length: 12,
    default: FlagStatus.OPEN,
  })
  status!: FlagStatus;

  /**
   * Human-readable description of why this flag was raised.
   */
  @Column({ type: 'text' })
  description!: string;

  /**
   * Machine-readable context (e.g., org names, role lists, diff details).
   */
  @Column({ type: 'jsonb', nullable: true })
  metadata?: Record<string, unknown>;

  /**
   * ID of the related entity that caused this flag.
   * E.g., ModerationIncident.id, RsiSyncAuditLog.id.
   */
  @Column({ type: 'uuid', nullable: true })
  relatedEntityId?: string;

  /**
   * Type label for the related entity (e.g., 'moderation_incident', 'rsi_sync').
   */
  @Column({ type: 'varchar', length: 50, nullable: true })
  relatedEntityType?: string;

  /**
   * Whether this flag was auto-generated by a detection hook
   * (vs. manually created by an intel officer).
   */
  @Column({ type: 'boolean', default: true })
  isAutoGenerated!: boolean;

  /**
   * User ID of the officer who resolved/dismissed/escalated this flag.
   */
  @Column({ type: 'varchar', nullable: true })
  resolvedBy?: string;

  /**
   * When the flag was resolved.
   */
  @Column({ type: 'timestamp', nullable: true })
  resolvedAt?: Date;

  /**
   * Officer's note when resolving/dismissing.
   */
  @Column({ type: 'text', nullable: true })
  resolutionNote?: string;

  @CreateDateColumn()
  createdAt!: Date;

  @UpdateDateColumn()
  updatedAt!: Date;

  // ==================== HELPER METHODS ====================

  /**
   * Whether this flag is still open (unresolved).
   */
  isOpen(): boolean {
    return this.status === FlagStatus.OPEN;
  }

  /**
   * Get the numeric severity weight for sorting/comparison.
   */
  getSeverityWeight(): number {
    const weights: Record<FlagSeverity, number> = {
      [FlagSeverity.INFO]: 1,
      [FlagSeverity.MEDIUM]: 2,
      [FlagSeverity.HIGH]: 3,
      [FlagSeverity.CRITICAL]: 4,
    };
    return weights[this.severity] ?? 0;
  }

  /**
   * Get the default severity for a given flag type.
   */
  static getDefaultSeverity(flagType: MemberFlagType): FlagSeverity {
    return DEFAULT_FLAG_SEVERITY[flagType] ?? FlagSeverity.MEDIUM;
  }

  /**
   * Get a human-readable label for the flag type.
   */
  static getFlagTypeLabel(flagType: MemberFlagType): string {
    const labels: Record<MemberFlagType, string> = {
      [MemberFlagType.RSI_ORG_LEFT]: 'Left RSI Organization',
      [MemberFlagType.JOINED_HOSTILE_ORG]: 'Joined Hostile Organization',
      [MemberFlagType.JOINED_REDACTED_ORG]: 'Joined Redacted Organization',
      [MemberFlagType.RSI_RANK_CHANGED]: 'RSI Rank Changed',
      [MemberFlagType.DISCORD_LEFT]: 'Left Discord Server',
      [MemberFlagType.DISCORD_ROLE_CHANGED]: 'Discord Roles Changed',
      [MemberFlagType.MODERATION_ACTION_RECEIVED]: 'Moderation Action Received',
      [MemberFlagType.MODERATION_ACTION_SHARED]: 'Shared Moderation Action',
      [MemberFlagType.PRIMARY_ORG_SWITCHED]: 'Primary Org Switched',
      [MemberFlagType.PLATFORM_LEFT]: 'Left Platform',
      [MemberFlagType.MANUAL]: 'Manual Flag',
      [MemberFlagType.RSI_HANDLE_CHANGED]: 'RSI Handle Changed',
      [MemberFlagType.IMPERSONATION_SUSPECTED]: 'Impersonation Suspected',
      [MemberFlagType.RSI_SYNC_FAILED]: 'RSI Sync Failed',
      [MemberFlagType.RSI_ORG_DISSOLVED]: 'RSI Organization Dissolved',
      [MemberFlagType.DISCORD_UNLINKED]: 'Discord Account Unlinked',
      [MemberFlagType.TEAM_MEMBER_REMOVED]: 'Team Member Removed',
      [MemberFlagType.TEAM_DELETED_WITH_MEMBERS]: 'Team Deleted With Members',
      [MemberFlagType.ACTIVITY_CANCELLED]: 'Activity Cancelled',
      // RSI Sync Intel Flags (Wave 3.3)
      [MemberFlagType.MISSING_FROM_RSI]: 'Missing From RSI Org',
      [MemberFlagType.MISSING_FROM_DISCORD]: 'Missing From Discord',
      [MemberFlagType.MISSING_FROM_WEB_APP]: 'Missing From Web App',
      [MemberFlagType.ROLE_MISMATCH_DISCORD]: 'Discord Role Mismatch',
      [MemberFlagType.ROLE_MISMATCH_INTERNAL]: 'Internal Role Mismatch',
      [MemberFlagType.HIDDEN_RSI_MEMBER]: 'Hidden RSI Member',
      [MemberFlagType.AFFILIATE_NOT_PRIMARY]: 'Affiliate (Not Primary)',
      [MemberFlagType.RSI_NOT_VERIFIED]: 'RSI Not Verified',
    };
    return labels[flagType] ?? flagType;
  }
}
