import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, Index} from 'typeorm';

/**
 * Types of changes that can occur in a relationship
 */
export enum ChangeType {
    CREATED = 'created',
    TYPE_CHANGED = 'type_changed',
    STATUS_CHANGED = 'status_changed',
    TRUST_UPDATED = 'trust_updated',
    STRENGTH_UPDATED = 'strength_updated',
    INTERACTION_RECORDED = 'interaction_recorded',
    METADATA_UPDATED = 'metadata_updated',
    NOTES_UPDATED = 'notes_updated',
    CONTACT_UPDATED = 'contact_updated',
    REVIEW_SCHEDULED = 'review_scheduled',
    EXPIRED = 'expired',
    RENEWED = 'renewed',
    SUSPENDED = 'suspended',
    REACTIVATED = 'reactivated',
    TERMINATED = 'terminated',
    MUTUAL_ESTABLISHED = 'mutual_established',
    MUTUAL_BROKEN = 'mutual_broken',
    CUSTOM = 'custom'
}

/**
 * Interaction sentiment for tracking positive/negative interactions
 */
export enum InteractionSentiment {
    VERY_POSITIVE = 'very_positive',
    POSITIVE = 'positive',
    NEUTRAL = 'neutral',
    NEGATIVE = 'negative',
    VERY_NEGATIVE = 'very_negative'
}

/**
 * Relationship history and changelog tracking
 * Maintains complete audit trail of all relationship changes
 */
@Entity('relationship_history')
@Index(['relationshipId', 'createdAt'])
@Index(['organizationId', 'targetOrganizationId'])
@Index(['changeType'])
@Index(['actorId'])
export class RelationshipHistory {
    @PrimaryGeneratedColumn('uuid')
    id!: string;

    @Index()
    @Column()
    relationshipId!: string;

    @Index()
    @Column()
    organizationId!: string;

    @Index()
    @Column()
    targetOrganizationId!: string;

    @Column({
        type: 'varchar',
        enum: ChangeType
    })
    changeType!: ChangeType;

    // Change Details
    @Column({ type: 'text' })
    description!: string;

    @Column({ type: 'simple-json', nullable: true })
    previousValue?: unknown; // Previous value before change

    @Column({ type: 'simple-json', nullable: true })
    newValue?: unknown; // New value after change

    @Column({ type: 'simple-json', nullable: true })
    changeDetails?: {
        trustScoreDelta?: number;
        strengthDelta?: number;
        interactionType?: string;
        sentiment?: InteractionSentiment;
        impact?: 'high' | 'medium' | 'low';
        automated?: boolean;
        customData?: Record<string, unknown>;
    };

    // Actor Information
    @Column({ nullable: true })
    actorId?: string; // User ID who made the change

    @Column({ nullable: true })
    actorName?: string; // Name of the actor

    @Column({ nullable: true })
    actorRole?: string; // Role of the actor

    // Context
    @Column({ type: 'text', nullable: true })
    reason?: string; // Reason for the change

    @Column({ type: 'text', nullable: true })
    notes?: string; // Additional notes

    @Column({ type: 'simple-array', nullable: true })
    tags?: string[];

    // Metadata
    @Column({ type: 'simple-json', nullable: true })
    metadata?: {
        ipAddress?: string;
        userAgent?: string;
        location?: string;
        source?: string; // UI, API, automation, etc.
        relatedEventId?: string;
        relatedActivityId?: string;
        customFields?: Record<string, unknown>;
    };

    // Flags
    @Column({ default: false })
    isSystemGenerated!: boolean; // Auto-generated by system

    @Column({ default: false })
    isSignificant!: boolean; // Mark as significant change

    @Column({ default: false })
    requiresNotification!: boolean; // Should notify relevant parties

    @Column({ default: false })
    notificationSent!: boolean;

    @CreateDateColumn()
    createdAt!: Date;

    // Methods for analysis

    /**
     * Get sentiment score (-2 to +2)
     */
    getSentimentScore(): number {
        if (!this.changeDetails?.sentiment) {return 0;}
        
        const sentimentScores: Record<InteractionSentiment, number> = {
            [InteractionSentiment.VERY_POSITIVE]: 2,
            [InteractionSentiment.POSITIVE]: 1,
            [InteractionSentiment.NEUTRAL]: 0,
            [InteractionSentiment.NEGATIVE]: -1,
            [InteractionSentiment.VERY_NEGATIVE]: -2
        };

        return sentimentScores[this.changeDetails.sentiment];
    }

    /**
     * Check if this is a positive change
     */
    isPositiveChange(): boolean {
        const positiveTypes = [
            ChangeType.CREATED,
            ChangeType.REACTIVATED,
            ChangeType.RENEWED,
            ChangeType.MUTUAL_ESTABLISHED
        ];

        if (positiveTypes.includes(this.changeType)) {return true;}
        if (this.changeType === ChangeType.TRUST_UPDATED && (this.changeDetails?.trustScoreDelta || 0) > 0) {return true;}
        if (this.changeType === ChangeType.STRENGTH_UPDATED && (this.changeDetails?.strengthDelta || 0) > 0) {return true;}
        if (this.changeType === ChangeType.INTERACTION_RECORDED) {
            const sentiment = this.changeDetails?.sentiment;
            return sentiment === InteractionSentiment.POSITIVE || sentiment === InteractionSentiment.VERY_POSITIVE;
        }

        return false;
    }

    /**
     * Check if this is a negative change
     */
    isNegativeChange(): boolean {
        const negativeTypes = [
            ChangeType.TERMINATED,
            ChangeType.SUSPENDED,
            ChangeType.EXPIRED,
            ChangeType.MUTUAL_BROKEN
        ];

        if (negativeTypes.includes(this.changeType)) {return true;}
        if (this.changeType === ChangeType.TRUST_UPDATED && (this.changeDetails?.trustScoreDelta || 0) < 0) {return true;}
        if (this.changeType === ChangeType.STRENGTH_UPDATED && (this.changeDetails?.strengthDelta || 0) < 0) {return true;}
        if (this.changeType === ChangeType.INTERACTION_RECORDED) {
            const sentiment = this.changeDetails?.sentiment;
            return sentiment === InteractionSentiment.NEGATIVE || sentiment === InteractionSentiment.VERY_NEGATIVE;
        }

        return false;
    }

    /**
     * Get impact level
     */
    getImpactLevel(): 'high' | 'medium' | 'low' {
        if (this.changeDetails?.impact) {return this.changeDetails.impact;}

        // Determine impact based on change type
        const highImpactTypes = [
            ChangeType.CREATED,
            ChangeType.TERMINATED,
            ChangeType.TYPE_CHANGED,
            ChangeType.MUTUAL_ESTABLISHED,
            ChangeType.MUTUAL_BROKEN
        ];

        if (highImpactTypes.includes(this.changeType)) {return 'high';}

        // Check for significant metric changes
        if (Math.abs(this.changeDetails?.trustScoreDelta || 0) >= 10) {return 'high';}
        if (Math.abs(this.changeDetails?.strengthDelta || 0) >= 10) {return 'high';}

        if (this.changeType === ChangeType.STATUS_CHANGED) {return 'medium';}
        
        return 'low';
    }

    /**
     * Get formatted change summary
     */
    getChangeSummary(): string {
        const summaries: Record<ChangeType, string> = {
            [ChangeType.CREATED]: 'Relationship established',
            [ChangeType.TYPE_CHANGED]: `Changed from ${this.previousValue} to ${this.newValue}`,
            [ChangeType.STATUS_CHANGED]: `Status changed from ${this.previousValue} to ${this.newValue}`,
            [ChangeType.TRUST_UPDATED]: `Trust score ${(this.changeDetails?.trustScoreDelta || 0) > 0 ? 'increased' : 'decreased'} by ${Math.abs(this.changeDetails?.trustScoreDelta || 0)}`,
            [ChangeType.STRENGTH_UPDATED]: `Relationship strength ${(this.changeDetails?.strengthDelta || 0) > 0 ? 'increased' : 'decreased'} by ${Math.abs(this.changeDetails?.strengthDelta || 0)}`,
            [ChangeType.INTERACTION_RECORDED]: `${this.changeDetails?.sentiment || 'Neutral'} interaction recorded`,
            [ChangeType.METADATA_UPDATED]: 'Metadata updated',
            [ChangeType.NOTES_UPDATED]: 'Notes updated',
            [ChangeType.CONTACT_UPDATED]: 'Contact information updated',
            [ChangeType.REVIEW_SCHEDULED]: 'Review scheduled',
            [ChangeType.EXPIRED]: 'Relationship expired',
            [ChangeType.RENEWED]: 'Relationship renewed',
            [ChangeType.SUSPENDED]: 'Relationship suspended',
            [ChangeType.REACTIVATED]: 'Relationship reactivated',
            [ChangeType.TERMINATED]: 'Relationship terminated',
            [ChangeType.MUTUAL_ESTABLISHED]: 'Mutual relationship established',
            [ChangeType.MUTUAL_BROKEN]: 'Mutual relationship broken',
            [ChangeType.CUSTOM]: this.description
        };

        return summaries[this.changeType] || this.description;
    }

    /**
     * Get detailed summary for API response
     */
    getDetailedSummary(): Record<string, unknown> {
        return {
            id: this.id,
            relationshipId: this.relationshipId,
            changeType: this.changeType,
            summary: this.getChangeSummary(),
            description: this.description,
            previousValue: this.previousValue,
            newValue: this.newValue,
            impact: this.getImpactLevel(),
            isPositive: this.isPositiveChange(),
            isNegative: this.isNegativeChange(),
            sentimentScore: this.getSentimentScore(),
            actor: {
                id: this.actorId,
                name: this.actorName,
                role: this.actorRole
            },
            reason: this.reason,
            notes: this.notes,
            tags: this.tags,
            isSystemGenerated: this.isSystemGenerated,
            isSignificant: this.isSignificant,
            createdAt: this.createdAt,
            changeDetails: this.changeDetails
        };
    }
}
