import { MigrationInterface, QueryRunner, Table, TableIndex } from 'typeorm';

/**
 * CreateMemberAuditAndWatchlist
 *
 * Wave 2.1 — Membership Audit & Intel
 *
 * Creates two tables:
 * 1. member_audit_events — behavioral flags for org members
 * 2. org_watchlist_entries — external RSI orgs an org wants to monitor
 *
 * Both tables are tenant-scoped via organizationId.
 * Uses varchar enums (not PG enums) for flexibility — matches syncStatus pattern.
 */
export class CreateMemberAuditAndWatchlist1774000000000 implements MigrationInterface {
  name = 'CreateMemberAuditAndWatchlist1774000000000';

  private async resolveColumnName(
    queryRunner: QueryRunner,
    tableName: string,
    preferredName: string
  ): Promise<string | null> {
    const rows = await queryRunner.query(
      `SELECT column_name
       FROM information_schema.columns
       WHERE table_schema = 'public'
         AND table_name = $1
         AND LOWER(column_name) = LOWER($2)
       ORDER BY CASE WHEN column_name = $2 THEN 0 ELSE 1 END
       LIMIT 1`,
      [tableName, preferredName]
    );

    return rows[0]?.column_name ?? null;
  }

  public async up(queryRunner: QueryRunner): Promise<void> {
    const auditTableExists = await queryRunner.hasTable('member_audit_events');
    const watchlistTableExists = await queryRunner.hasTable('org_watchlist_entries');

    if (auditTableExists && watchlistTableExists) {
      const auditOrgColumn = await this.resolveColumnName(
        queryRunner,
        'member_audit_events',
        'organizationId'
      );
      const watchlistOrgColumn = await this.resolveColumnName(
        queryRunner,
        'org_watchlist_entries',
        'organizationId'
      );

      if (auditOrgColumn && watchlistOrgColumn) {
        return;
      }
    }

    // ──────────────────────────────────────────────────────────
    // 1. member_audit_events
    // ──────────────────────────────────────────────────────────
    await queryRunner.createTable(
      new Table({
        name: 'member_audit_events',
        columns: [
          {
            name: 'id',
            type: 'uuid',
            isPrimary: true,
            generationStrategy: 'uuid',
            default: 'uuid_generate_v4()',
          },
          {
            name: 'organizationId',
            type: 'varchar',
            isNullable: false,
          },
          {
            name: 'userId',
            type: 'varchar',
            isNullable: false,
          },
          {
            name: 'flagType',
            type: 'varchar',
            length: '40',
            isNullable: false,
          },
          {
            name: 'severity',
            type: 'varchar',
            length: '10',
            isNullable: false,
          },
          {
            name: 'status',
            type: 'varchar',
            length: '12',
            isNullable: false,
            default: `'open'`,
          },
          {
            name: 'description',
            type: 'text',
            isNullable: false,
          },
          {
            name: 'metadata',
            type: 'jsonb',
            isNullable: true,
          },
          {
            name: 'relatedEntityId',
            type: 'uuid',
            isNullable: true,
          },
          {
            name: 'relatedEntityType',
            type: 'varchar',
            length: '50',
            isNullable: true,
          },
          {
            name: 'isAutoGenerated',
            type: 'boolean',
            default: true,
          },
          {
            name: 'resolvedBy',
            type: 'uuid',
            isNullable: true,
          },
          {
            name: 'resolvedAt',
            type: 'timestamp',
            isNullable: true,
          },
          {
            name: 'resolutionNote',
            type: 'text',
            isNullable: true,
          },
          // TenantEntity columns
          {
            name: 'sharedWithOrgs',
            type: 'text',
            isNullable: true,
            default: `''`,
          },
          {
            name: 'deletedAt',
            type: 'timestamp',
            isNullable: true,
          },
          {
            name: 'deletedBy',
            type: 'varchar',
            isNullable: true,
          },
          {
            name: 'createdAt',
            type: 'timestamp',
            default: 'now()',
          },
          {
            name: 'updatedAt',
            type: 'timestamp',
            default: 'now()',
          },
        ],
      }),
      true
    );

    // Indexes for member_audit_events
    const auditIndexes: { name: string; columnNames: string[] }[] = [
      { name: 'IDX_mae_org_id', columnNames: ['organizationId'] },
      { name: 'IDX_mae_user_id', columnNames: ['userId'] },
      { name: 'IDX_mae_org_user', columnNames: ['organizationId', 'userId'] },
      { name: 'IDX_mae_org_status', columnNames: ['organizationId', 'status'] },
      { name: 'IDX_mae_org_flag_type', columnNames: ['organizationId', 'flagType'] },
      { name: 'IDX_mae_org_severity', columnNames: ['organizationId', 'severity'] },
      { name: 'IDX_mae_org_created', columnNames: ['organizationId', 'createdAt'] },
      { name: 'IDX_mae_user_flag_type', columnNames: ['userId', 'flagType'] },
      { name: 'IDX_mae_status', columnNames: ['status'] },
    ];

    for (const idx of auditIndexes) {
      await queryRunner.createIndex(
        'member_audit_events',
        new TableIndex({ name: idx.name, columnNames: idx.columnNames })
      );
    }

    // ──────────────────────────────────────────────────────────
    // 2. org_watchlist_entries
    // ──────────────────────────────────────────────────────────
    await queryRunner.createTable(
      new Table({
        name: 'org_watchlist_entries',
        columns: [
          {
            name: 'id',
            type: 'uuid',
            isPrimary: true,
            generationStrategy: 'uuid',
            default: 'uuid_generate_v4()',
          },
          {
            name: 'organizationId',
            type: 'varchar',
            isNullable: false,
          },
          {
            name: 'rsiOrgSid',
            type: 'varchar',
            length: '100',
            isNullable: false,
          },
          {
            name: 'rsiOrgName',
            type: 'varchar',
            length: '255',
            isNullable: false,
          },
          {
            name: 'reason',
            type: 'varchar',
            length: '30',
            isNullable: false,
          },
          {
            name: 'threatLevel',
            type: 'varchar',
            length: '12',
            isNullable: false,
          },
          {
            name: 'notes',
            type: 'text',
            isNullable: true,
          },
          {
            name: 'addedBy',
            type: 'uuid',
            isNullable: false,
          },
          // TenantEntity columns
          {
            name: 'sharedWithOrgs',
            type: 'text',
            isNullable: true,
            default: `''`,
          },
          {
            name: 'deletedAt',
            type: 'timestamp',
            isNullable: true,
          },
          {
            name: 'deletedBy',
            type: 'varchar',
            isNullable: true,
          },
          {
            name: 'createdAt',
            type: 'timestamp',
            default: 'now()',
          },
          {
            name: 'updatedAt',
            type: 'timestamp',
            default: 'now()',
          },
        ],
      }),
      true
    );

    // Indexes for org_watchlist_entries
    const watchlistIndexes: { name: string; columnNames: string[]; isUnique?: boolean }[] = [
      { name: 'IDX_owe_org_id', columnNames: ['organizationId'] },
      { name: 'IDX_owe_org_sid', columnNames: ['organizationId', 'rsiOrgSid'], isUnique: true },
      { name: 'IDX_owe_org_reason', columnNames: ['organizationId', 'reason'] },
      { name: 'IDX_owe_org_threat', columnNames: ['organizationId', 'threatLevel'] },
      { name: 'IDX_owe_rsi_sid', columnNames: ['rsiOrgSid'] },
    ];

    for (const idx of watchlistIndexes) {
      await queryRunner.createIndex(
        'org_watchlist_entries',
        new TableIndex({
          name: idx.name,
          columnNames: idx.columnNames,
          isUnique: idx.isUnique ?? false,
        })
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropTable('org_watchlist_entries', true);
    await queryRunner.dropTable('member_audit_events', true);
  }
}
