/**
 * Phase B tests — MemberAuditService (flag engine) and domain event wiring.
 *
 * These tests verify:
 *  1. MemberAuditService CRUD (create, list, resolve, stats)
 *  2. Domain event → flag auto-creation for all 9 subscribed events
 *  3. Watchlist cross-reference escalation (hostile / redacted / other)
 *  4. Moderation severity mapping
 *  5. Role change description builder
 *
 * Database calls are mocked (no real DB connection needed).
 */

import {
  DEFAULT_FLAG_SEVERITY,
  FlagSeverity,
  FlagStatus,
  MemberFlagType,
  WatchlistReason,
  WatchlistThreatLevel,
} from '@sc-fleet-manager/shared-types';

/* ------------------------------------------------------------------ */
/*  Mocks — must be defined BEFORE imports that use them               */
/* ------------------------------------------------------------------ */

// AppDataSource mock
const mockFlagRepo = {
  create: jest.fn((data: Record<string, unknown>) => ({ id: 'flag-1', ...data })),
  save: jest.fn((entity: Record<string, unknown>) =>
    Promise.resolve({ ...entity, id: entity.id ?? 'flag-1' })
  ),
  findOne: jest.fn(),
  find: jest.fn(),
  createQueryBuilder: jest.fn(),
};

const mockWatchlistRepo = {
  findOne: jest.fn(),
};

jest.mock('../../../data-source', () => ({
  AppDataSource: {
    getRepository: jest.fn((entity: { name?: string } | (new () => unknown)) => {
      const name = typeof entity === 'function' ? entity.name : entity?.name;
      if (name === 'MemberAuditEvent') return mockFlagRepo;
      if (name === 'OrgWatchlistEntry') return mockWatchlistRepo;
      return {};
    }),
  },
}));

jest.mock('../../../utils/logger', () => ({
  logger: {
    info: jest.fn(),
    debug: jest.fn(),
    warn: jest.fn(),
    error: jest.fn(),
  },
}));

// Mock DomainEventBus — use real implementation but reset singleton
jest.mock('../../../services/shared/DomainEventBus', () => {
  const actual = jest.requireActual('../../../services/shared/DomainEventBus');
  // Reset singleton so tests get a fresh bus
  actual.DomainEventBus.resetInstance();
  const bus = actual.DomainEventBus.getInstance();
  return {
    ...actual,
    domainEvents: bus,
  };
});

/* ------------------------------------------------------------------ */
/*  Imports (after mocks)                                              */
/* ------------------------------------------------------------------ */

import { MemberAuditService } from '../../../services/intel/MemberAuditService';
import { domainEvents } from '../../../services/shared/DomainEventBus';

/* ------------------------------------------------------------------ */
/*  Helpers                                                            */
/* ------------------------------------------------------------------ */

const ORG_ID = 'org-test-001';
const USER_ID = 'user-test-001';

/** Flush microtask queue so async event handlers complete. */
const flushAsync = () => new Promise<void>(r => setTimeout(r, 10));

/* ------------------------------------------------------------------ */
/*  Test Suite                                                         */
/* ------------------------------------------------------------------ */

describe('MemberAuditService (Phase B)', () => {
  let service: MemberAuditService;

  beforeEach(() => {
    jest.clearAllMocks();

    // Remove all listeners added by the previous test's service
    domainEvents.removeAllListeners();

    service = new MemberAuditService();
    service.subscribeToEvents();
  });

  // ────────────────────────────────────────────────────────────
  //  CRUD
  // ────────────────────────────────────────────────────────────

  describe('createFlag', () => {
    it('should create a flag with default severity when none provided', async () => {
      await service.createFlag({
        userId: USER_ID,
        organizationId: ORG_ID,
        flagType: MemberFlagType.RSI_ORG_LEFT,
        description: 'Test flag',
      });

      expect(mockFlagRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          userId: USER_ID,
          organizationId: ORG_ID,
          flagType: MemberFlagType.RSI_ORG_LEFT,
          severity: DEFAULT_FLAG_SEVERITY[MemberFlagType.RSI_ORG_LEFT],
          status: FlagStatus.OPEN,
          isAutoGenerated: true,
        })
      );
      expect(mockFlagRepo.save).toHaveBeenCalled();
    });

    it('should use provided severity over default', async () => {
      await service.createFlag({
        userId: USER_ID,
        organizationId: ORG_ID,
        flagType: MemberFlagType.DISCORD_LEFT,
        severity: FlagSeverity.CRITICAL,
        description: 'Banned',
      });

      expect(mockFlagRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          severity: FlagSeverity.CRITICAL,
        })
      );
    });
  });

  describe('createManualFlag', () => {
    it('should create a manual flag with isAutoGenerated=false', async () => {
      await service.createManualFlag(ORG_ID, USER_ID, 'officer-1', {
        userId: USER_ID,
        severity: FlagSeverity.HIGH,
        description: 'Suspicious activity',
      });

      expect(mockFlagRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          flagType: MemberFlagType.MANUAL,
          isAutoGenerated: false,
          metadata: expect.objectContaining({
            createdByOfficer: 'officer-1',
          }),
        })
      );
    });
  });

  describe('resolveFlag', () => {
    it('should resolve an open flag', async () => {
      const mockFlag = {
        id: 'flag-1',
        organizationId: ORG_ID,
        status: FlagStatus.OPEN,
        isOpen: () => true,
      };
      mockFlagRepo.findOne.mockResolvedValueOnce(mockFlag);
      mockFlagRepo.save.mockResolvedValueOnce({ ...mockFlag, status: FlagStatus.RESOLVED });

      const result = await service.resolveFlag(ORG_ID, 'flag-1', 'officer-1', {
        status: FlagStatus.RESOLVED,
        resolutionNote: 'Reviewed and cleared',
      });

      expect(result.status).toBe(FlagStatus.RESOLVED);
      expect(mockFlag).toHaveProperty('resolvedBy', 'officer-1');
    });

    it('should throw when flag not found', async () => {
      mockFlagRepo.findOne.mockResolvedValueOnce(null);

      await expect(
        service.resolveFlag(ORG_ID, 'nope', 'officer-1', {
          status: FlagStatus.DISMISSED,
          resolutionNote: 'Not relevant',
        })
      ).rejects.toThrow('Flag not found');
    });

    it('should throw when flag is already resolved', async () => {
      const mockFlag = {
        id: 'flag-1',
        organizationId: ORG_ID,
        status: FlagStatus.RESOLVED,
        isOpen: () => false,
      };
      mockFlagRepo.findOne.mockResolvedValueOnce(mockFlag);

      await expect(
        service.resolveFlag(ORG_ID, 'flag-1', 'officer-1', {
          status: FlagStatus.ESCALATED,
          resolutionNote: 'N/A',
        })
      ).rejects.toThrow('Flag is already resolved');
    });
  });

  describe('getUserFlagStats', () => {
    it('should aggregate flag stats', async () => {
      const now = new Date();
      mockFlagRepo.find.mockResolvedValueOnce([
        {
          severity: FlagSeverity.HIGH,
          status: FlagStatus.OPEN,
          createdAt: now,
          getSeverityWeight: () => 3,
        },
        {
          severity: FlagSeverity.INFO,
          status: FlagStatus.RESOLVED,
          createdAt: now,
          getSeverityWeight: () => 1,
        },
        {
          severity: FlagSeverity.CRITICAL,
          status: FlagStatus.ESCALATED,
          createdAt: now,
          getSeverityWeight: () => 4,
        },
      ]);

      const stats = await service.getUserFlagStats(ORG_ID, USER_ID);

      expect(stats.totalFlags).toBe(3);
      expect(stats.openFlags).toBe(1);
      expect(stats.resolvedFlags).toBe(1);
      expect(stats.escalatedFlags).toBe(1);
      expect(stats.dismissedFlags).toBe(0);
      expect(stats.highestSeverity).toBe(FlagSeverity.CRITICAL);
      expect(stats.lastFlagAt).toBe(now.toISOString());
    });

    it('should handle zero flags', async () => {
      mockFlagRepo.find.mockResolvedValueOnce([]);

      const stats = await service.getUserFlagStats(ORG_ID, USER_ID);

      expect(stats.totalFlags).toBe(0);
      expect(stats.highestSeverity).toBeNull();
      expect(stats.lastFlagAt).toBeNull();
    });
  });

  // ────────────────────────────────────────────────────────────
  //  Domain Event → Flag Auto-Creation
  // ────────────────────────────────────────────────────────────

  describe('Domain event subscriptions', () => {
    it('should create DISCORD_LEFT flag on member:discord_left', async () => {
      domainEvents.emit('member:discord_left', {
        timestamp: new Date().toISOString(),
        userId: USER_ID,
        discordId: '123456',
        discordUsername: 'testuser',
        guildId: 'guild-1',
        guildName: 'Test Guild',
        organizationId: ORG_ID,
        reason: 'leave',
      });
      await flushAsync();

      expect(mockFlagRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          flagType: MemberFlagType.DISCORD_LEFT,
          userId: USER_ID,
          organizationId: ORG_ID,
        })
      );
    });

    it('should elevate severity to CRITICAL for ban', async () => {
      domainEvents.emit('member:discord_left', {
        timestamp: new Date().toISOString(),
        userId: USER_ID,
        discordId: '123456',
        discordUsername: 'banned-user',
        guildId: 'guild-1',
        guildName: 'Test Guild',
        organizationId: ORG_ID,
        reason: 'ban',
      });
      await flushAsync();

      expect(mockFlagRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          severity: FlagSeverity.CRITICAL,
        })
      );
    });

    it('should elevate severity to HIGH for kick', async () => {
      domainEvents.emit('member:discord_left', {
        timestamp: new Date().toISOString(),
        userId: USER_ID,
        discordId: '123456',
        discordUsername: 'kicked-user',
        guildId: 'guild-1',
        guildName: 'Test Guild',
        organizationId: ORG_ID,
        reason: 'kick',
      });
      await flushAsync();

      expect(mockFlagRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          severity: FlagSeverity.HIGH,
        })
      );
    });

    it('should create DISCORD_ROLE_CHANGED flag on member:discord_role_changed', async () => {
      domainEvents.emit('member:discord_role_changed', {
        timestamp: new Date().toISOString(),
        userId: USER_ID,
        discordId: '123456',
        guildId: 'guild-1',
        organizationId: ORG_ID,
        addedRoles: ['role-1'],
        removedRoles: ['role-2'],
      });
      await flushAsync();

      expect(mockFlagRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          flagType: MemberFlagType.DISCORD_ROLE_CHANGED,
          description: expect.stringContaining('added: 1 role(s)'),
        })
      );
    });

    it('should create MODERATION_ACTION_RECEIVED flag on member:discord_timeout', async () => {
      domainEvents.emit('member:discord_timeout', {
        timestamp: new Date().toISOString(),
        userId: USER_ID,
        discordId: '123456',
        guildId: 'guild-1',
        guildName: 'Test Guild',
        organizationId: ORG_ID,
        durationMinutes: 60,
        reason: 'Being disruptive',
      });
      await flushAsync();

      expect(mockFlagRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          flagType: MemberFlagType.MODERATION_ACTION_RECEIVED,
          severity: FlagSeverity.HIGH,
        })
      );
    });

    it('should create RSI_ORG_LEFT flag on member:rsi_org_left', async () => {
      domainEvents.emit('member:rsi_org_left', {
        timestamp: new Date().toISOString(),
        userId: USER_ID,
        organizationId: ORG_ID,
        rsiHandle: 'testpilot',
        rsiOrgSid: 'TESTORG',
        rsiOrgName: 'Test Organization',
      });
      await flushAsync();

      expect(mockFlagRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          flagType: MemberFlagType.RSI_ORG_LEFT,
          description: expect.stringContaining('TESTORG'),
        })
      );
    });

    it('should create RSI_RANK_CHANGED flag on member:rsi_rank_changed', async () => {
      domainEvents.emit('member:rsi_rank_changed', {
        timestamp: new Date().toISOString(),
        userId: USER_ID,
        organizationId: ORG_ID,
        rsiHandle: 'testpilot',
        rsiOrgSid: 'TESTORG',
        oldRank: 'Member',
        newRank: 'Officer',
      });
      await flushAsync();

      expect(mockFlagRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          flagType: MemberFlagType.RSI_RANK_CHANGED,
          severity: DEFAULT_FLAG_SEVERITY[MemberFlagType.RSI_RANK_CHANGED],
          description: expect.stringContaining('Member'),
        })
      );
    });

    it('should create PRIMARY_ORG_SWITCHED flag on member:primary_org_switched (previous org)', async () => {
      domainEvents.emit('member:primary_org_switched', {
        timestamp: new Date().toISOString(),
        userId: USER_ID,
        previousOrgId: ORG_ID,
        newOrgId: 'org-other',
      });
      await flushAsync();

      expect(mockFlagRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          flagType: MemberFlagType.PRIMARY_ORG_SWITCHED,
          organizationId: ORG_ID,
        })
      );
    });

    it('should NOT create flag when previousOrgId is null', async () => {
      domainEvents.emit('member:primary_org_switched', {
        timestamp: new Date().toISOString(),
        userId: USER_ID,
        previousOrgId: null,
        newOrgId: 'org-new',
      });
      await flushAsync();

      expect(mockFlagRepo.create).not.toHaveBeenCalled();
    });

    it('should create PLATFORM_LEFT flag on member:platform_left', async () => {
      domainEvents.emit('member:platform_left', {
        timestamp: new Date().toISOString(),
        userId: USER_ID,
        organizationId: ORG_ID,
        username: 'departing_user',
      });
      await flushAsync();

      expect(mockFlagRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          flagType: MemberFlagType.PLATFORM_LEFT,
          severity: FlagSeverity.CRITICAL,
        })
      );
    });
  });

  // ────────────────────────────────────────────────────────────
  //  Moderation action events
  // ────────────────────────────────────────────────────────────

  describe('Moderation action handling', () => {
    it('should create MODERATION_ACTION_RECEIVED for local action', async () => {
      domainEvents.emit('member:moderation_action', {
        timestamp: new Date().toISOString(),
        userId: USER_ID,
        organizationId: ORG_ID,
        incidentId: 'inc-1',
        incidentType: 'ban',
        severity: 8,
        moderatorId: 'mod-1',
        reason: 'Toxicity',
        isShared: false,
      });
      await flushAsync();

      expect(mockFlagRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          flagType: MemberFlagType.MODERATION_ACTION_RECEIVED,
          severity: FlagSeverity.CRITICAL, // severity 8 → CRITICAL
          relatedEntityId: 'inc-1',
          relatedEntityType: 'moderation_incident',
        })
      );
    });

    it('should create MODERATION_ACTION_SHARED for shared action', async () => {
      domainEvents.emit('member:moderation_action', {
        timestamp: new Date().toISOString(),
        userId: USER_ID,
        organizationId: ORG_ID,
        incidentId: 'inc-2',
        incidentType: 'timeout',
        severity: 3,
        moderatorId: 'mod-1',
        isShared: true,
      });
      await flushAsync();

      expect(mockFlagRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          flagType: MemberFlagType.MODERATION_ACTION_SHARED,
          severity: FlagSeverity.MEDIUM, // severity 3 → MEDIUM
        })
      );
    });

    it('should map severity thresholds correctly', async () => {
      // severity 1 → INFO
      domainEvents.emit('member:moderation_action', {
        timestamp: new Date().toISOString(),
        userId: USER_ID,
        organizationId: ORG_ID,
        incidentId: 'inc-3',
        incidentType: 'warning',
        severity: 1,
        moderatorId: 'mod-1',
        isShared: false,
      });
      await flushAsync();

      expect(mockFlagRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          severity: FlagSeverity.INFO,
        })
      );
    });
  });

  // ────────────────────────────────────────────────────────────
  //  Watchlist cross-reference
  // ────────────────────────────────────────────────────────────

  describe('RSI org joined — watchlist cross-reference', () => {
    const joinPayload = {
      timestamp: new Date().toISOString(),
      userId: USER_ID,
      organizationId: ORG_ID,
      rsiHandle: 'testpilot',
      rsiOrgSid: 'HOSTILE_ORG',
      rsiOrgName: 'Hostile Pirates',
      isHostile: false,
      isRedacted: false,
    };

    it('should create JOINED_HOSTILE_ORG flag when payload isHostile=true', async () => {
      mockWatchlistRepo.findOne.mockResolvedValueOnce(null);

      domainEvents.emit('member:rsi_org_joined', {
        ...joinPayload,
        isHostile: true,
      });
      await flushAsync();

      expect(mockFlagRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          flagType: MemberFlagType.JOINED_HOSTILE_ORG,
          severity: FlagSeverity.CRITICAL,
        })
      );
    });

    it('should create JOINED_REDACTED_ORG flag when payload isRedacted=true', async () => {
      mockWatchlistRepo.findOne.mockResolvedValueOnce(null);

      domainEvents.emit('member:rsi_org_joined', {
        ...joinPayload,
        isRedacted: true,
      });
      await flushAsync();

      expect(mockFlagRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          flagType: MemberFlagType.JOINED_REDACTED_ORG,
          severity: FlagSeverity.HIGH,
        })
      );
    });

    it('should ignore watchlist entries when payload is not hostile/redacted', async () => {
      mockWatchlistRepo.findOne.mockResolvedValueOnce({
        reason: WatchlistReason.HOSTILE,
        threatLevel: WatchlistThreatLevel.CRITICAL,
        getFlagSeverity: () => 'critical',
      });

      domainEvents.emit('member:rsi_org_joined', joinPayload);
      await flushAsync();

      expect(mockFlagRepo.create).not.toHaveBeenCalled();
      expect(mockWatchlistRepo.findOne).not.toHaveBeenCalled();
    });

    it('should not create flag for suspicious watchlist entries without hostile/redacted payload', async () => {
      mockWatchlistRepo.findOne.mockResolvedValueOnce({
        reason: WatchlistReason.SUSPICIOUS,
        threatLevel: WatchlistThreatLevel.MODERATE,
        getFlagSeverity: () => 'medium',
      });

      domainEvents.emit('member:rsi_org_joined', joinPayload);
      await flushAsync();

      expect(mockFlagRepo.create).not.toHaveBeenCalled();
      expect(mockWatchlistRepo.findOne).not.toHaveBeenCalled();
    });

    it('should NOT create flag when org is not on watchlist and not hostile/redacted', async () => {
      mockWatchlistRepo.findOne.mockResolvedValueOnce(null);

      domainEvents.emit('member:rsi_org_joined', joinPayload);
      await flushAsync();

      expect(mockFlagRepo.create).not.toHaveBeenCalled();
    });
  });

  // ────────────────────────────────────────────────────────────
  //  Idempotent subscription
  // ────────────────────────────────────────────────────────────

  describe('subscribeToEvents', () => {
    it('should be idempotent — calling twice does not double-subscribe', async () => {
      // The service already called subscribeToEvents() in beforeEach.
      // Call again — the second call should be a no-op.
      service.subscribeToEvents();

      // Emit a single event
      jest.clearAllMocks();
      domainEvents.emit('member:rsi_org_left', {
        timestamp: new Date().toISOString(),
        userId: USER_ID,
        organizationId: ORG_ID,
        rsiHandle: 'test',
        rsiOrgSid: 'TEST',
        rsiOrgName: 'Test',
      });
      await flushAsync();

      // Should only create ONE flag (not two) proving idempotency
      expect(mockFlagRepo.create).toHaveBeenCalledTimes(1);
    });
  });
});
