import type { Meta, StoryObj } from '@storybook/react';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { Breadcrumbs, SimpleBreadcrumbs } from './Breadcrumbs';

export const meta: Meta<typeof Breadcrumbs> = {
  title: 'UI/Breadcrumbs',
  component: Breadcrumbs,
  parameters: {
    layout: 'padded',
  },
  tags: ['autodocs'],
  decorators: [
    (Story) => (
      <MemoryRouter>
        <Story />
      </MemoryRouter>
    ),
  ],
  argTypes: {
    showHomeIcon: {
      control: 'boolean',
      description: 'Show home icon for the first breadcrumb',
    },
    maxItems: {
      control: 'number',
      description: 'Maximum items to show before collapsing',
    },
  },
};

type Story = StoryObj<typeof meta>;

export const AutoGenerated: Story = {
  name: 'Auto-Generated from Route',
  decorators: [
    (Story) => (
      <MemoryRouter initialEntries={['/fleet/ships/edit']}>
        <Routes>
          <Route path="/fleet/ships/edit" element={<Story />} />
        </Routes>
      </MemoryRouter>
    ),
  ],
  args: {},
};

export const CustomItems: Story = {
  args: {
    items: [
      { label: 'Dashboard', path: '/' },
      { label: 'Fleet Management', path: '/fleet' },
      { label: 'Edit Ship' },
    ],
  },
};

export const DeepNavigation: Story = {
  name: 'Deep Navigation Path',
  decorators: [
    (Story) => (
      <MemoryRouter initialEntries={['/organizations/alpha-squadron/members/profile/settings']}>
        <Routes>
          <Route path="/organizations/alpha-squadron/members/profile/settings" element={<Story />} />
        </Routes>
      </MemoryRouter>
    ),
  ],
  args: {},
};

export const WithoutHomeIcon: Story = {
  args: {
    items: [
      { label: 'Dashboard', path: '/' },
      { label: 'Fleet', path: '/fleet' },
      { label: 'Ships' },
    ],
    showHomeIcon: false,
  },
};

export const AdminSection: Story = {
  name: 'Admin Section Example',
  args: {
    items: [
      { label: 'Dashboard', path: '/' },
      { label: 'Admin', path: '/admin' },
      { label: 'Users', path: '/admin/users' },
      { label: 'Permissions' },
    ],
  },
};

export const TradingSection: Story = {
  name: 'Trading Section Example',
  args: {
    items: [
      { label: 'Dashboard', path: '/' },
      { label: 'Trading', path: '/trading' },
      { label: 'Routes', path: '/trading/routes' },
      { label: 'Create Route' },
    ],
  },
};

export const WithCollapse: Story = {
  name: 'Collapsed (Max 4 Items)',
  args: {
    items: [
      { label: 'Dashboard', path: '/' },
      { label: 'Organizations', path: '/organizations' },
      { label: 'Alpha Squadron', path: '/organizations/alpha' },
      { label: 'Members', path: '/organizations/alpha/members' },
      { label: 'Profile', path: '/organizations/alpha/members/profile' },
      { label: 'Settings', path: '/organizations/alpha/members/profile/settings' },
      { label: 'Security' },
    ],
    maxItems: 4,
  },
};

export const SimpleBreadcrumbsVariant: Story = {
  name: 'Simple Breadcrumbs (No Spectrum)',
  render: () => (
    <MemoryRouter>
      <SimpleBreadcrumbs
        items={[
          { label: 'Dashboard', path: '/' },
          { label: 'Fleet', path: '/fleet' },
          { label: 'Ships' },
        ]}
      />
    </MemoryRouter>
  ),
};

export const DetailsPage: Story = {
  name: 'Details Page with UUID',
  decorators: [
    (Story) => (
      <MemoryRouter initialEntries={['/fleet/abc12345-6789-0def-1234-56789abcdef0']}>
        <Routes>
          <Route path="/fleet/:id" element={<Story />} />
        </Routes>
      </MemoryRouter>
    ),
  ],
  args: {},
};

export const AllRouteExamples: Story = {
  name: 'Multiple Route Examples',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
      <div>
        <div style={{ color: '#8a9eb5', marginBottom: '0.5rem', fontSize: '0.875rem' }}>
          Fleet Management
        </div>
        <MemoryRouter>
          <Breadcrumbs
            items={[
              { label: 'Dashboard', path: '/' },
              { label: 'Fleet', path: '/fleet' },
              { label: 'Ships' },
            ]}
          />
        </MemoryRouter>
      </div>
      
      <div>
        <div style={{ color: '#8a9eb5', marginBottom: '0.5rem', fontSize: '0.875rem' }}>
          Organization Settings
        </div>
        <MemoryRouter>
          <Breadcrumbs
            items={[
              { label: 'Dashboard', path: '/' },
              { label: 'Organizations', path: '/organizations' },
              { label: 'Alpha Squadron', path: '/organizations/alpha' },
              { label: 'Settings' },
            ]}
          />
        </MemoryRouter>
      </div>
      
      <div>
        <div style={{ color: '#8a9eb5', marginBottom: '0.5rem', fontSize: '0.875rem' }}>
          Logistics Inventory
        </div>
        <MemoryRouter>
          <Breadcrumbs
            items={[
              { label: 'Dashboard', path: '/' },
              { label: 'Logistics', path: '/logistics' },
              { label: 'Inventory', path: '/logistics/inventory' },
              { label: 'View Item' },
            ]}
          />
        </MemoryRouter>
      </div>
    </div>
  ),
};
