import { Verifier } from '@pact-foundation/pact';
import path from 'path';
import { createServer, Server } from 'http';
import express, { Express } from 'express';

/**
 * Provider State Setup
 * 
 * This file contains provider state setup functions that ensure the backend
 * is in the correct state for each consumer contract test.
 * 
 * Each state corresponds to a "state" declaration in the consumer tests.
 */

export interface ProviderState {
  state: string;
  action: 'setup' | 'teardown';
  params?: Record<string, any>;
}

/**
 * Mock data for provider states
 */
const mockData = {
  fleets: [
    {
      id: 'fleet-123',
      name: 'Alpha Squadron',
      description: 'Primary combat squadron',
      organizationId: 'org-123',
      createdAt: new Date('2024-01-01T00:00:00.000Z').toISOString(),
      updatedAt: new Date('2024-01-01T00:00:00.000Z').toISOString(),
    },
  ],
  organizations: [
    {
      id: 'org-123',
      name: 'Star Citizen Fleet',
      description: 'Primary fleet organization',
      type: 'FLEET',
      status: 'ACTIVE',
      createdAt: new Date('2024-01-01T00:00:00.000Z').toISOString(),
      updatedAt: new Date('2024-01-01T00:00:00.000Z').toISOString(),
    },
  ],
  users: [
    {
      id: 'user-123',
      username: 'testuser',
      email: 'testuser@example.com',
      role: 'USER',
      createdAt: new Date('2024-01-01T00:00:00.000Z').toISOString(),
      updatedAt: new Date('2024-01-01T00:00:00.000Z').toISOString(),
    },
  ],
};

/**
 * Create a mock Express app for provider state setup
 * This app provides endpoints that the Pact verifier can call to set up state
 */
export const createProviderStateApp = (): Express => {
  const app = express();
  app.use(express.json());

  /**
   * Provider state endpoint
   * This endpoint is called by the Pact verifier to set up state before each test
   */
  app.post('/pact-setup', (req, res) => {
    const { state, action, params } = req.body as ProviderState;

    console.log(`[Pact] State setup: ${state} (${action})`);

    try {
      // Handle setup actions
      if (action === 'setup') {
        switch (state) {
          // Fleet states
          case 'fleets exist for organization':
          case 'fleet exists with id fleet-123':
          case 'organization has fleets with statistics':
            // Mock data is already set up
            break;

          case 'fleet does not exist':
            // Nothing to set up - test expects 404
            break;

          // Organization states
          case 'organizations exist':
          case 'organization exists with id org-123':
          case 'organization exists with members':
            // Mock data is already set up
            break;

          case 'organization does not exist':
            // Nothing to set up - test expects 404
            break;

          case 'organization exists with id org-123 and can be deleted':
            // Mock data is already set up
            break;

          // User states
          case 'user exists with id user-123':
          case 'user exists with profile':
          case 'user exists with preferences':
          case 'user has activity history':
          case 'user has organizations':
          case 'users exist matching search criteria':
            // Mock data is already set up
            break;

          case 'user does not exist':
            // Nothing to set up - test expects 404
            break;

          // Authentication states
          case 'user is authenticated':
          case 'user is authenticated and has organization':
            // Mock authentication is handled by middleware
            break;

          default:
            console.warn(`[Pact] Unknown state: ${state}`);
        }
      }

      res.status(200).json({ result: 'success' });
    } catch (error) {
      console.error(`[Pact] Error setting up state: ${error}`);
      res.status(500).json({ error: 'State setup failed' });
    }
  });

  return app;
};

/**
 * Configuration for Pact verification
 */
export const getVerifierOptions = (): any => {
  const pactDir = path.resolve(__dirname, '..', '..', '..', '..', 'pacts');
  
  return {
    provider: 'FleetManagerBackend',
    providerBaseUrl: process.env.PROVIDER_URL || 'http://localhost:3000',
    
    // Location of pact files (generated by consumer tests)
    pactUrls: [
      path.join(pactDir, 'FleetManagerFrontend-FleetManagerBackend.json'),
    ],
    
    // Provider states endpoint - using direct state handlers instead of HTTP endpoint
    // This avoids the need for a separate state server
    stateHandlers: {
      // Handler for each provider state
      'fleets exist for organization': async () => {
        console.log('[Pact] Setting up state: fleets exist for organization');
        // State is already set up with mock data
        return Promise.resolve('State setup complete');
      },
      'fleet exists with id fleet-123': async () => {
        console.log('[Pact] Setting up state: fleet exists with id fleet-123');
        return Promise.resolve('State setup complete');
      },
      'fleet does not exist': async () => {
        console.log('[Pact] Setting up state: fleet does not exist');
        return Promise.resolve('State setup complete');
      },
      'organization has fleets with statistics': async () => {
        console.log('[Pact] Setting up state: organization has fleets with statistics');
        return Promise.resolve('State setup complete');
      },
      'organizations exist': async () => {
        console.log('[Pact] Setting up state: organizations exist');
        return Promise.resolve('State setup complete');
      },
      'organization exists with id org-123': async () => {
        console.log('[Pact] Setting up state: organization exists with id org-123');
        return Promise.resolve('State setup complete');
      },
      'organization does not exist': async () => {
        console.log('[Pact] Setting up state: organization does not exist');
        return Promise.resolve('State setup complete');
      },
      'organization exists with members': async () => {
        console.log('[Pact] Setting up state: organization exists with members');
        return Promise.resolve('State setup complete');
      },
      'organization exists with id org-123 and can be deleted': async () => {
        console.log('[Pact] Setting up state: organization exists with id org-123 and can be deleted');
        return Promise.resolve('State setup complete');
      },
      'user exists with id user-123': async () => {
        console.log('[Pact] Setting up state: user exists with id user-123');
        return Promise.resolve('State setup complete');
      },
      'user does not exist': async () => {
        console.log('[Pact] Setting up state: user does not exist');
        return Promise.resolve('State setup complete');
      },
      'user exists with profile': async () => {
        console.log('[Pact] Setting up state: user exists with profile');
        return Promise.resolve('State setup complete');
      },
      'user exists with preferences': async () => {
        console.log('[Pact] Setting up state: user exists with preferences');
        return Promise.resolve('State setup complete');
      },
      'user has activity history': async () => {
        console.log('[Pact] Setting up state: user has activity history');
        return Promise.resolve('State setup complete');
      },
      'user has organizations': async () => {
        console.log('[Pact] Setting up state: user has organizations');
        return Promise.resolve('State setup complete');
      },
      'users exist matching search criteria': async () => {
        console.log('[Pact] Setting up state: users exist matching search criteria');
        return Promise.resolve('State setup complete');
      },
      'user is authenticated': async () => {
        console.log('[Pact] Setting up state: user is authenticated');
        return Promise.resolve('State setup complete');
      },
      'user is authenticated and has organization': async () => {
        console.log('[Pact] Setting up state: user is authenticated and has organization');
        return Promise.resolve('State setup complete');
      },
    },
    
    // Logging
    logLevel: 'debug', // Increased logging for debugging
    
    // Publishing configuration (optional)
    publishVerificationResult: process.env.CI === 'true',
    providerVersion: process.env.GIT_COMMIT || 'dev',
    
    // Timeout settings - increase for CI environments
    timeout: 60000, // 60 seconds
    
    // Request filters to add authentication headers
    requestFilter: (req: any, res: any, next: any) => {
      // Add authentication headers for protected endpoints
      req.headers['Authorization'] = 'Bearer mock-token';
      next();
    },
  };
};
